### ISSUE TITLE
How can we set this bot for private users ?

### ISSUE THREAD

**Issue by telegrambotdev** [hemantapkh/TorrentHunt#1]
How can make this bot work only for a specific user ? can you please tell ?

anyway the bot is great

**Comment by hemantapkh** [comment]
For that you need to ignore the message from other users. You can implement it by adding `if message.from_user.id != _yourId_:
        pass ` [here](https://github.com/hemantapkh/TorrentHunt/blob/cf194ea3925d6ef8f06f37256aec0c9a847e1c1d/torrenthunt.py#L419). Also, do the similar thing for inline query [here](https://github.com/hemantapkh/TorrentHunt/blob/cf194ea3925d6ef8f06f37256aec0c9a847e1c1d/torrenthunt.py#L604).

**Comment by telegrambotdev** [comment]
> For that you need to ignore the message from other users. You can implement it by adding `if message.from_user.id != _yourId_: pass ` [here](https://github.com/hemantapkh/TorrentHunt/blob/cf194ea3925d6ef8f06f37256aec0c9a847e1c1d/torrenthunt.py#L419). Also, do the similar thing for inline query [here](https://github.com/hemantapkh/TorrentHunt/blob/cf194ea3925d6ef8f06f37256aec0c9a847e1c1d/torrenthunt.py#L604).

not working,after i adding that still anyone can accees the bot

**Comment by hemantapkh** [comment]
Did you changed the `if` statement to `elif` [here](https://github.com/hemantapkh/TorrentHunt/blob/10b77f7a755065e2a0e44fd7ae8f97de77afba34/torrenthunt.py#L482)?

**Comment by telegrambotdev** [comment]
> Did you changed the `if` statement to `elif` [here](https://github.com/hemantapkh/TorrentHunt/blob/10b77f7a755065e2a0e44fd7ae8f97de77afba34/torrenthunt.py#L482)?

yeah did that.getting this error

```
[+] Database opened successfully.
[+] Table users created successfully.
[+] Table settings created successfully.
Traceback (most recent call last):
  File "torrenthunt.py", line 737, in <module>
    bot.polling(none_stop=True)
  File "/usr/local/lib/python3.8/dist-packages/telebot/__init__.py", line 514, in polling
    self.__threaded_polling(none_stop, interval, timeout, long_polling_timeout)
  File "/usr/local/lib/python3.8/dist-packages/telebot/__init__.py", line 573, in __threaded_polling
    raise e
  File "/usr/local/lib/python3.8/dist-packages/telebot/__init__.py", line 536, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "/usr/local/lib/python3.8/dist-packages/telebot/util.py", line 117, in raise_exceptions
    raise self.exception_info
  File "/usr/local/lib/python3.8/dist-packages/telebot/util.py", line 69, in run
    task(*args, **kwargs)
  File "torrenthunt.py", line 507, in text
    if message.from_user.id != test:12345
NameError: name 'test' is not defined
```

This the my repo,can you check where is the error ?

https://github.com/telegrambotdev/TorrentHunt/blob/main/torrenthunt.py

**Comment by hemantapkh** [comment]
Suppose your userId is 12345

```
if message.from_user.id != 12345:
    pass
```

**Comment by telegrambotdev** [comment]
Worked. Thanks alot. once again great work !
