### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by mjain234** [hemantapkh/TorrentHunt#15]
recently i have been only trying and trying  to deploy this torrent search bot on my vps and ultimately caught with this error:
Traceback (most recent call last):
  File "torrenthunt.py", line 5, in <module>
    from src import *
  File "/home/ubuntu/torrenthunt/src/__init__.py", line 2, in <module>
    from src.objs import config, dbSql
  File "/home/ubuntu/torrenthunt/src/objs.py", line 12, in <module>
    config = json.load(open(configPath))
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 2 column 27 (char 28)

**Comment by hemantapkh** [comment]
Error in your config files.
