### ISSUE TITLE
TypeError: gather() got an unexpected keyword argument 'loop'

### ISSUE THREAD

**Issue by xon54** [hemantapkh/TorrentHunt#16]
/home/ubuntu/TorrentHunt/torrenthunt.py:95: DeprecationWarning: ssl.PROTOCOL_TLSv1_2 is deprecated
  context = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)
Traceback (most recent call last):
  File "/home/ubuntu/TorrentHunt/env/lib/python3.10/site-packages/aiohttp/web.py", line 508, in run_app
    loop.run_until_complete(main_task)
  File "/usr/lib/python3.10/asyncio/base_events.py", line
646, in run_until_complete
    return future.result()
  File "/home/ubuntu/TorrentHunt/env/lib/python3.10/site-packages/aiohttp/web.py", line 411, in _run_app
    await site.start()
  File "/home/ubuntu/TorrentHunt/env/lib/python3.10/site-packages/aiohttp/web_runner.py", line 121, in start
    self._server = await loop.create_server(
  File "/usr/lib/python3.10/asyncio/base_events.py", line
1505, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 99] error while attempting to bind on address ('129.146.253.192', 80): cannot assign requested address
During handling of the above exception, another exception
occurred:
Traceback (most recent call last):
  File "/home/ubuntu/TorrentHunt/torrenthunt.py", line 99, in <module>
    web.run_app(
  File "/home/ubuntu/TorrentHunt/env/lib/python3.10/site-packages/aiohttp/web.py", line 512, in run_app
    _cancel_tasks({main_task}, loop)
  File "/home/ubuntu/TorrentHunt/env/lib/python3.10/site-packages/aiohttp/web.py", line 444, in _cancel_tasks
    asyncio.gather(*to_cancel, loop=loop, return_exceptions=True)
TypeError: gather() got an unexpected keyword argument 'loop'

Anyway to fix it

**Comment by hemantapkh** [comment]
Please use the latest version.
