### ISSUE TITLE
How to deploy as a docker container ?

### ISSUE THREAD

**Issue by joxnr33** [hemantapkh/TorrentHunt#9]
hey there , i am new to programming in general and i was wondering how can i deploy this as a docker container . i tried to deploy on heroku by creating a dokerfile and built an image .But when i ran the container i got the following error :

`Traceback (most recent call last):
File "/app/torrenthunt.py", line 86, in <module>
bot.polling(none_stop=True)
File "/usr/local/lib/python3.10/site-packages/telebot/__init__.py", line 633, in polling
self.__threaded_polling(non_stop, interval, timeout, long_polling_timeout, allowed_updates)
File "/usr/local/lib/python3.10/site-packages/telebot/__init__.py", line 692, in __threaded_polling
 raise e
File "/usr/local/lib/python3.10/site-packages/telebot/__init__.py", line 655, in __threaded_polling
self.worker_pool.raise_exceptions()
File "/usr/local/lib/python3.10/site-packages/telebot/util.py", line 130, in raise_exceptions
 raise self.exception_info
File "/usr/local/lib/python3.10/site-packages/telebot/util.py", line 82, in run
task(*args, **kwargs)
 File "/app/src/commands/start.py", line 10, in start
 if dbSql.setAccount(message.chat.id, message.chat.username):
File "/app/models.py", line 16, in setAccount
 isRegistered = self.isRegistered(userId, chatType)
File "/app/models.py", line 37, in isRegistered
isRegistered = cur.execute(f'SELECT * FROM {chatType} WHERE userId={userId}').fetchone()
 sqlite3.OperationalError: no such table: users`

it seems that the sqlite db is not being created properly or it is not created at all . i dont know for sure as i dont know much about python and databases . if you can help me out with this , that would be great .

anyways great work brother and i hope you will continue bringing us great projects like this in future also .

**Comment by hemantapkh** [comment]
Running migrations.py (`python3 migrations.py`) will open the database but I don't think this will work on Heroku cause it don't support sqlite.

**Comment by joxnr33** [comment]
Oh , that's unfortunate . Thanks for your response , do let me know if there is a workaround . Feel free to close this issue if there is none . Have a good day
